require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Max: 150

Rails/CreateTableWithTimestamps:
  Exclude:
    - "db/migrate/20201226150556_create_active_storage_tables.active_storage.rb"
