plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

Layout/LineLength:
  Max: 150

Rails/CreateTableWithTimestamps:
  Exclude:
    - "db/migrate/20201226150556_create_active_storage_tables.active_storage.rb"
    - "db/migrate/20220125164010_create_active_storage_variant_records.active_storage.rb"

Rails/SkipsModelValidations:
  AllowedMethods:
    - "increment!"
    - "decrement!"
    - "update_column"
    - "update_all"

Style/MultilineBlockChain:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - "lib/tasks/pandemiccms.rake"

RSpec/AnyInstance:
  Enabled: false

Style/ClassVars:
  Exclude:
    - "app/services/asset_path_fetcher.rb"

RSpec/IndexedLet:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Style/Documentation:
  Enabled: false
