default: &default
  dispatchers:
    - polling_interval: 5
      batch_size: 500
  workers:
    - queues: "*"
      threads: 1
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
