# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

default: &default
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  index_all:
    class: IndexAllJob
    args: ["", true]
    schedule: every 5 minutes
  delete_old_events:
    class: DeleteOldEventsJob
    args: [""]
    schedule: every 1 hour

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
