default: &default
  type: "<%= Rails.application.credentials.dig(:search, :type) %>"
  url: "<%= Rails.application.credentials.dig(:search, :url) %>"
  username: "<%= Rails.application.credentials.dig(:search, :username) %>"
  password: "<%= Rails.application.credentials.dig(:search, :password) %>"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default