default: &default
  type: database

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  type: elasticsearch
  url: http://elasticsearch:9200
  username: elastic
  password: "1234"