# default: &default

development:
  # <<: *default
  local:
    id: "local"
    name: "Pandemic CMS"
    release_year: 2020
    domains:
      - "localhost"

test:
  # <<: *default
  local:
    id: "local"
    name: "Pandemic CMS"
    release_year: 2020
    domains:
      - "localhost"
      - "example.com"

production:
  # <<: *default
