development:
  local:
    id: "local"
    name: "Pandemic CMS"
    default_url_options:
      host: "localhost"
      port: 3000
    locales:
      en:
        name: "English"
        code: "🇬🇧"
      el:
        name: "Ελληνικά"
        code: "🇬🇷"
    domains:
      - "localhost"

test:
  local:
    id: "local"
    name: "Pandemic CMS"
    default_url_options:
      host: "localhost"
      port: 3000
    locales:
      en:
        name: "English"
        code: "🇬🇧"
    domains:
      - "localhost"
      - "example.com"

production:
  local:
    id: "local"
    name: "Pandemic CMS"
    default_url_options:
      host: "raspberrypi.local"
      port: 80
    locales:
      en:
        name: "English"
        code: "🇬🇧"
      el:
        name: "Ελληνικά"
        code: "🇬🇷"
    domains:
      - "raspberrypi.local"
