# default: &default

development:
  # <<: *default
  local:
    id: "local"
    name: "Pandemic CMS"
    release_year: 2020
    default_url_options:
      host: "localhost"
      port: 3000
    locales:
      en:
        name: "English"
        code: "🇬🇧"
      el:
        name: "Ελληνικά"
        code: "🇬🇷"
    domains:
      - "localhost"

test:
  # <<: *default
  local:
    id: "local"
    name: "Pandemic CMS"
    release_year: 2020
    default_url_options:
      host: "localhost"
      port: 3000
    locales:
      en:
        name: "English"
        code: "🇬🇧"
    domains:
      - "localhost"
      - "example.com"

production:
  # <<: *default
