name: Build

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Ruby 3.4.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'
          bundler-cache: true
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'pnpm'
      - name: Install Ruby dependencies
        run: bundle
      - name: Install NodeJS dependencies
        run: pnpm i
      - name: Run Rubocop
        run: bundle exec rubocop
      - name: Run ESLint
        run: pnpm lint
      - name: Test
        run: bundle exec rspec
      - name: Build
        run: bundle exec rails assets:precompile